### ISSUE TITLE
not starting

### ISSUE THREAD

**Issue by norbie18** [TheFamousPG/chrome-extension-grepolis-tools#2]
it doesn't start when i click start. the timer doesnt begin. sometimes it works but not always.
can u fix this?

**Comment by TheFamousPG** [comment]
Can you tell me when the error occurs? (The page that does not work,
your configuration in the game and your game server?)

On what browser are you?
Do you have an error on the browser console ?
(https://developer.chrome.com/devtools/docs/tips-and-tricks)
(https://developer.mozilla.org/en-US/docs/Tools/Browser_Console)

**Comment by norbie18** [comment]
the error occurs almost every time, my game server is nl44
im playing on chrome i can send the errors on console, i will post in tomorrow

**Comment by norbie18** [comment]
http://i65.tinypic.com/2lufcsw.png

**Comment by TheFamousPG** [comment]
Have you try to disabled all of your extension except this ? And clear cache

**Comment by norbie18** [comment]
yea and stil got the same problem

**Comment by TheFamousPG** [comment]
Can you show me the entire console log message.
